name: NeedTown
version: 2.7
main: me.jacklin213.needtown.NeedTown
description: Need a town? Just ask for it!
author: jacklin213
authors: [BMX_ATVMAN14, jacklin213]

softdepend: [Towny]

commands:
  needtown:
    description: Allows people to use the NeedTown command
    permission: needtown.use
    aliases: nt
    usage: The correct usage is /needtown or /nt
  needtownr:
    description: Reload Command for console
    aliases: ntr

permissions:
  needtown.*:
    description: Allows use of all needtown commands
    default: op
    children:
      needtown.use: true
      needtown.users: true
      needtown.reload: true
      needtown.op: true
  needtown.op:
    description: Allows use Most of the needtown commands
    default: op
    children:
      needtown.use: true
      needtown.users: true
      needtown.reload: true
  needtown.use:
    description: Allows people use needtown
    default: true
  needtown.users:
    description: Allows people to list users who need a town
    default: op
  needtown.reload:
    description: Allows people to reload config
    default: op
  